// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tournament-planner/BullpenStack.tsx": () => import("../components/mockups/tournament-planner/BullpenStack.tsx"),
  "./components/mockups/tournament-planner/MatrixGrid.tsx": () => import("../components/mockups/tournament-planner/MatrixGrid.tsx"),
  "./components/mockups/tournament-planner/TimelineRail.tsx": () => import("../components/mockups/tournament-planner/TimelineRail.tsx")
};
